---
- name: Deploy CV Docker Container
  hosts: debian_agents
  become: yes

  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Start Docker service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Create project directory
      file:
        path: ~/Ansible
        state: directory

    - name: Copy Dockerfile to agent
      copy:
        src: ~/Ansible/Dockerfile
        dest: ~/Ansible/Dockerfile

    - name: Copy index.html to agent
      copy:
        src: ~/Ansible/index.html
        dest: ~/Ansible/index.html

    - name: Build Docker image
      command: docker build -t resume_image ~/Ansible

    - name: Run Docker container
      command: docker run -d --name my_resume -p 82:80 resume_image
